[package]
name = "jute"
version = "0.1.0"
authors = ["salad <fmoenne-@student.le-101.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "*"
